Team_message= '§eDu willst dem Team joinen? Bewirb dich jetzt bei uns, via Minecraft Chat, oder E-Mail.'

no_perm= '§cDu bist nicht berechtigt diesen Befehl auszuführen'

no_console= '§cNur Spieler können diesen Befehl ausführen'
